name: Windows build

on:
  push:
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  REPO_DIR: ${{ github.workspace }}
  BUILD_DIR: ${{ github.workspace }}/bin/builddir
  BOOST_VERSION: "1.78.0"
  BOOST_INSTALL_DIR: "${{ github.workspace }}/bin"

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Build Environment
        shell: pwsh
        run: |
          cmake -E make_directory "${{ env.BUILD_DIR }}"

      - name: Install boost
        uses: MarkusJx/install-boost@v2
        id: install-boost
        with:
          boost_version: ${{ env.BOOST_VERSION }}
          platform_version: 2022
          toolset: msvc
          boost_install_dir: ${{ env.BOOST_INSTALL_DIR }}

      - name: Export BOOST_ROOT
        shell: pwsh
        run: |
          "BOOST_ROOT=${{ steps.install-boost.outputs.BOOST_ROOT }}" >> $env:GITHUB_ENV

      - name: Configure
        shell: pwsh
        run: |
          cmake -B "${{ env.BUILD_DIR }}" -S "${{ env.REPO_DIR }}" -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build
        shell: pwsh
        run: |
          cmake --build "${{ env.BUILD_DIR }}" --config ${{ env.BUILD_TYPE }}

      - name: Archive files
        shell: pwsh
        run: |
          cd bin
          7z a -tzip snapshot.zip x64_Release

      - name: Archive this artefact
        uses: actions/upload-artifact@v4
        with:
          name: snapshot
          path: bin/snapshot.zip

  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs:
      - build
    if: failure()

    steps:
      - name: Notify
        uses: rjstone/discord-webhook-notify@v1.0.4
        with:
          severity: error
          description: Windows build failed
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
